### PR TITLE
Fix results handling when multiple tests where run in one session.

### PR DESCRIPTION
**Pull request by krzycho1024**
Proper handling of duplicate records created by OpenCover.

### CODE REVIEW

**Comment by danielpalme** [comment]
Thanks for your PR. I will have a look at it within the next 1 or 2 weeks.
One question: When does OpenCover's output contain duplicate records?

**Comment by krzycho1024** [comment]
When we are running multiple XUnit2 tests in one session.
We are doing it using cake:
OpenCover(tool => tool.XUnit2(tests),
	new FilePath(coverageLocation + "/OpenCover.xml"),
	new OpenCoverSettings() {
		Register = "user",
		ArgumentCustomization = args=>args.Append("-coverbytest:*.Tests.dll").Append("-searchdirs:" + string.Join(";", pdbLocation))
		}
		.WithFilter("+[OurProject*]*")
	);

OpenCover creates multiple sections of same module:
<Module hash="64-92-C7-09-48-CC-7C-64-32-49-FA-6B-50-21-70-98-6F-CC-75-E3">
with different ModulePath
<ModulePath>C:\Users\myUser\AppData\Local\Temp\02c69fc7-efda-45d1-a584-657c3b852769\02c69fc7-efda-45d1-a584-657c3b852769\assembly\dl3\540a1d19\93389c27_7672d301\OurProject.Contract.dll</ModulePath>
<ModulePath>C:\OurProject\OurProject.Application.Tests\bin\debug\net462\OurProject.Contract.dll</ModulePath>

Without fix it creates messy report like:
<package name="OurProject.Contract" line-rate="0" branch-rate="0" complexity="0">
<package name="OurProject.Contract" line-rate="0.267676767676768" branch-rate="0.275" complexity="0">
<package name="OurProject.Contract" line-rate="0" branch-rate="0" complexity="0">
<package name="OurProject.Contract" line-rate="0.103535353535354" branch-rate="0.05" complexity="0">

also header isn't correct:
<coverage line-rate="0.219693388262308" branch-rate="0.179129464285714" lines-covered="3253" lines-valid="14807" branches-covered="642" branches-valid="3584" complexity="0" version="0" timestamp="1513003414">

After my fix it's:
<coverage line-rate="0.378833084700812" branch-rate="0.416470588235294" lines-covered="4571" lines-valid="12066" branches-covered="354" branches-valid="850" complexity="0" version="0" timestamp="1513011295">

After my fix differences between OpenCover and Cobertura in ReportGenrator are only in lines like:
var a = new {
    A = 1
};

with OpenCover counts as 3 lines and Cobertura counts as 1.

ReportGenerator handles properly OpenCover results but's gets only first <package> in Cobertura.

**Comment by danielpalme** [comment]
Now I understand your problem.
I think we don't have to make any changes to _OpenCoverToCoberturaConverter_.

When you execute _OpenCover_, just add the `-mergebyhash` command line switch/parameter.
Then OpenCover merges the results itself.
See: https://github.com/opencover/opencover/wiki/Usage#optional-arguments

**Comment by danielpalme** [comment]
@krzycho1024 
Did the `-mergebyhash` parameter fix your problem?

**Comment by krzycho1024** [comment]
@danielpalme Yes- adding this option solved the problem. Thanks for your help.

**Pull request closed without merging**
